CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_classes_updated
  BEFORE UPDATE ON classes
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

CREATE TRIGGER trg_instances_updated
  BEFORE UPDATE ON instances
  FOR EACH ROW EXECUTE FUNCTION update_timestamp();

ALTER TABLE classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE properties DISABLE ROW LEVEL SECURITY;
ALTER TABLE instances DISABLE ROW LEVEL SECURITY;
ALTER TABLE instance_values DISABLE ROW LEVEL SECURITY;
ALTER TABLE relation_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE edges DISABLE ROW LEVEL SECURITY;
ALTER TABLE axioms DISABLE ROW LEVEL SECURITY;
ALTER TABLE axiom_classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE commits DISABLE ROW LEVEL SECURITY;
ALTER TABLE commit_details DISABLE ROW LEVEL SECURITY;
